/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import java.sql.Connection;
import org.openswing.swing.client.DeleteButton;
import org.openswing.swing.client.EditButton;
import org.openswing.swing.client.SaveButton;
import org.openswing.swing.form.client.Form;
import org.openswing.swing.form.client.FormController;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class ClasseProdutoDetalhe extends InternalFrame {

    private Connection conn = null;

    /**
     * Creates new form IngredienteDetalhe
     */
    public ClasseProdutoDetalhe(Connection conn, FormController dataController) {
        try {
            this.conn = conn;
            initComponents();
            formDetalheClasseProd.setFormController(dataController);
            setSize(800, 600);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Form getForm1() {
        return formDetalheClasseProd;

    }

    public SaveButton getSaveButton() {
        return saveButton;
    }

    public DeleteButton getDeleteButton() {
        return deleteButton;
    }

    public EditButton getEditButton() {
        return editButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        copyButton = new org.openswing.swing.client.CopyButton();
        editButton = new org.openswing.swing.client.EditButton();
        deleteButton = new org.openswing.swing.client.DeleteButton();
        reloadButton = new org.openswing.swing.client.ReloadButton();
        saveButton = new org.openswing.swing.client.SaveButton();
        formDetalheClasseProd = new org.openswing.swing.form.client.Form();
        textNomeTipoClasse = new org.openswing.swing.client.TextControl();
        textCodClasse = new org.openswing.swing.client.TextControl();
        txtData_classe = new org.openswing.swing.client.LabelControl();
        txtNomeTipo = new org.openswing.swing.client.LabelControl();
        txtDescricaoClasse = new org.openswing.swing.client.LabelControl();
        dateControlClasse = new org.openswing.swing.client.DateControl();
        txtCod_classe = new org.openswing.swing.client.LabelControl();
        textAreaDescricaoClasse = new org.openswing.swing.client.TextAreaControl();
        txtNomeClasse1 = new org.openswing.swing.client.LabelControl();
        textNomeClasse = new org.openswing.swing.client.TextControl();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro das Classe de Produtos (Inserir/Alterar)");
        setFrameIcon(null);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery_Factory_logo_127x50.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel1.add(lblLogo);
        jPanel1.add(insertButton1);
        jPanel1.add(copyButton);
        jPanel1.add(editButton);
        jPanel1.add(deleteButton);
        jPanel1.add(reloadButton);
        jPanel1.add(saveButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        formDetalheClasseProd.setVOClassName("com.bakeryfactory.VO.ClasseProdutoVO");
        formDetalheClasseProd.setCopyButton(copyButton);
        formDetalheClasseProd.setDeleteButton(deleteButton);
        formDetalheClasseProd.setEditButton(editButton);
        formDetalheClasseProd.setFunctionId("classe_produtos");
        formDetalheClasseProd.setInsertButton(insertButton1);
        formDetalheClasseProd.setReloadButton(reloadButton);
        formDetalheClasseProd.setSaveButton(saveButton);
        formDetalheClasseProd.setLayout(new java.awt.GridBagLayout());

        textNomeTipoClasse.setAttributeName("tipoClasseProd");
        textNomeTipoClasse.setMaxCharacters(60);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formDetalheClasseProd.add(textNomeTipoClasse, gridBagConstraints);

        textCodClasse.setAttributeName("codClasseProd");
        textCodClasse.setEnabled(false);
        textCodClasse.setEnabledOnEdit(false);
        textCodClasse.setEnabledOnInsert(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 250);
        formDetalheClasseProd.add(textCodClasse, gridBagConstraints);

        txtData_classe.setText("Data de Cadastro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formDetalheClasseProd.add(txtData_classe, gridBagConstraints);

        txtNomeTipo.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formDetalheClasseProd.add(txtNomeTipo, gridBagConstraints);

        txtDescricaoClasse.setText("Descrição");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formDetalheClasseProd.add(txtDescricaoClasse, gridBagConstraints);

        dateControlClasse.setAttributeName("dataCadastroClasseProd");
        dateControlClasse.setCanCopy(false);
        dateControlClasse.setRequired(true);
        dateControlClasse.setToolTipText("Inserir Data de Cadastro do Ingrediente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formDetalheClasseProd.add(dateControlClasse, gridBagConstraints);

        txtCod_classe.setText("Código");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formDetalheClasseProd.add(txtCod_classe, gridBagConstraints);

        textAreaDescricaoClasse.setAttributeName("descricaoClasseProd");
        textAreaDescricaoClasse.setToolTipText("Insira a Descrição quando necessário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formDetalheClasseProd.add(textAreaDescricaoClasse, gridBagConstraints);

        txtNomeClasse1.setText("Classe Produto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formDetalheClasseProd.add(txtNomeClasse1, gridBagConstraints);

        textNomeClasse.setAttributeName("nomeClasseProd");
        textNomeClasse.setMaxCharacters(60);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formDetalheClasseProd.add(textNomeClasse, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        getContentPane().add(formDetalheClasseProd, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.CopyButton copyButton;
    private org.openswing.swing.client.DateControl dateControlClasse;
    private org.openswing.swing.client.DeleteButton deleteButton;
    private org.openswing.swing.client.EditButton editButton;
    private org.openswing.swing.form.client.Form formDetalheClasseProd;
    private org.openswing.swing.client.InsertButton insertButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private org.openswing.swing.client.ReloadButton reloadButton;
    private org.openswing.swing.client.SaveButton saveButton;
    private org.openswing.swing.client.TextAreaControl textAreaDescricaoClasse;
    private org.openswing.swing.client.TextControl textCodClasse;
    private org.openswing.swing.client.TextControl textNomeClasse;
    private org.openswing.swing.client.TextControl textNomeTipoClasse;
    private org.openswing.swing.client.LabelControl txtCod_classe;
    private org.openswing.swing.client.LabelControl txtData_classe;
    private org.openswing.swing.client.LabelControl txtDescricaoClasse;
    private org.openswing.swing.client.LabelControl txtNomeClasse1;
    private org.openswing.swing.client.LabelControl txtNomeTipo;
    // End of variables declaration//GEN-END:variables
}
