/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import com.bakeryfactory.Controller.ClasseProdutoController;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class ClasseProduto extends InternalFrame {

    private Connection conn = null;

    /**
     * Creates new form Ingredientes Panificadora
     */
    public ClasseProduto(Connection conn, ClasseProdutoController classeProdController) {
        this.conn = conn;
        try {
            initComponents();
            setSize(750, 300);
            gridControlClasseProd.setController(classeProdController);
            gridControlClasseProd.setGridDataLocator(classeProdController);
            //gridControlIngred.enableDrag("Grid1");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public void reloadData(){
        gridControlClasseProd.reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTituloFormDetalheController = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        insertButtonClasse = new org.openswing.swing.client.InsertButton();
        editButtonClasse = new org.openswing.swing.client.EditButton();
        deleteButtonClasse = new org.openswing.swing.client.DeleteButton();
        reloadButtonClasse = new org.openswing.swing.client.ReloadButton();
        exportButtonClasse = new org.openswing.swing.client.ExportButton();
        importButtonClasse = new org.openswing.swing.client.ImportButton();
        navigatorBarClasse = new org.openswing.swing.client.NavigatorBar();
        gridControlClasseProd = new org.openswing.swing.client.GridControl();
        dateClasseProd = new org.openswing.swing.table.columns.client.DateColumn();
        integerCodClasse = new org.openswing.swing.table.columns.client.IntegerColumn();
        textNomeClasseProd = new org.openswing.swing.table.columns.client.TextColumn();
        textColumnTipoClasseProd = new org.openswing.swing.table.columns.client.TextColumn();
        textDescricaoClasse = new org.openswing.swing.table.columns.client.TextColumn();

        setTitle("Classificação dos Produtos da Panificadora");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery_Factory_logo_127x50.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel1.add(lblLogo);

        lblTituloFormDetalheController.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        lblTituloFormDetalheController.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloFormDetalheController.setText("Classe de Produtos");
        jPanel1.add(lblTituloFormDetalheController);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.add(insertButtonClasse);
        jPanel2.add(editButtonClasse);
        jPanel2.add(deleteButtonClasse);
        jPanel2.add(reloadButtonClasse);
        jPanel2.add(exportButtonClasse);
        jPanel2.add(importButtonClasse);
        jPanel2.add(navigatorBarClasse);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        gridControlClasseProd.setDeleteButton(deleteButtonClasse);
        gridControlClasseProd.setExportButton(exportButtonClasse);
        gridControlClasseProd.setFunctionId("classe_produtos");
        gridControlClasseProd.setImportButton(importButtonClasse);
        gridControlClasseProd.setInsertButton(insertButtonClasse);
        gridControlClasseProd.setNavBar(navigatorBarClasse);
        gridControlClasseProd.setReloadButton(reloadButtonClasse);
        gridControlClasseProd.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControlClasseProd.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        dateClasseProd.setColumnSortable(true);
        dateClasseProd.setHeaderColumnName("Data");
        dateClasseProd.setSortVersus(org.openswing.swing.util.java.Consts.ASC_SORTED);
        gridControlClasseProd.getColumnContainer().add(dateClasseProd);

        integerCodClasse.setHeaderColumnName("Codigo");
        gridControlClasseProd.getColumnContainer().add(integerCodClasse);

        textNomeClasseProd.setColumnSortable(true);
        textNomeClasseProd.setHeaderColumnName("Nome Classe de Produtos");
        textNomeClasseProd.setPreferredWidth(300);
        gridControlClasseProd.getColumnContainer().add(textNomeClasseProd);

        textColumnTipoClasseProd.setHeaderColumnName("Tipo Classe");
        gridControlClasseProd.getColumnContainer().add(textColumnTipoClasseProd);

        textDescricaoClasse.setColumnSortable(true);
        textDescricaoClasse.setHeaderColumnName("Descrição Classe Produtos");
        textDescricaoClasse.setPreferredWidth(200);
        gridControlClasseProd.getColumnContainer().add(textDescricaoClasse);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControlClasseProd, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DateColumn dateClasseProd;
    private org.openswing.swing.client.DeleteButton deleteButtonClasse;
    private org.openswing.swing.client.EditButton editButtonClasse;
    private org.openswing.swing.client.ExportButton exportButtonClasse;
    private org.openswing.swing.client.GridControl gridControlClasseProd;
    private org.openswing.swing.client.ImportButton importButtonClasse;
    private org.openswing.swing.client.InsertButton insertButtonClasse;
    private org.openswing.swing.table.columns.client.IntegerColumn integerCodClasse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloFormDetalheController;
    private org.openswing.swing.client.NavigatorBar navigatorBarClasse;
    private org.openswing.swing.client.ReloadButton reloadButtonClasse;
    private org.openswing.swing.table.columns.client.TextColumn textColumnTipoClasseProd;
    private org.openswing.swing.table.columns.client.TextColumn textDescricaoClasse;
    private org.openswing.swing.table.columns.client.TextColumn textNomeClasseProd;
    // End of variables declaration//GEN-END:variables
}
