/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import com.bakeryfactory.view.Ingredientes;
import java.sql.Connection;
import org.openswing.swing.client.DeleteButton;
import org.openswing.swing.client.EditButton;
import org.openswing.swing.client.SaveButton;
import org.openswing.swing.form.client.Form;
import org.openswing.swing.form.client.FormController;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class CongeladosDetalhe extends InternalFrame {
    
    private Connection conn = null;

    public CongeladosDetalhe(Connection conn, FormController dataController) {
        try {
            this.conn = conn;
             initComponents();
             formCongelados.setFormController(dataController);
             setSize(590,440);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public Form getForm1(){
        return formCongelados;
        
    }
    
    public SaveButton getSaveButton() {
        return saveButtonCong;
    }

    public DeleteButton getDeleteButton() {
        return deleteButtonCong;
    }

    public EditButton getEditButton() {
        return editButtonCong;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        insertButtonCong = new org.openswing.swing.client.InsertButton();
        copyButtonCong = new org.openswing.swing.client.CopyButton();
        editButtonCong = new org.openswing.swing.client.EditButton();
        deleteButtonCong = new org.openswing.swing.client.DeleteButton();
        reloadButtonCong = new org.openswing.swing.client.ReloadButton();
        saveButtonCong = new org.openswing.swing.client.SaveButton();
        formCongelados = new org.openswing.swing.form.client.Form();
        textNomeIngred = new org.openswing.swing.client.TextControl();
        numericQuantCongelados = new org.openswing.swing.client.NumericControl();
        txtDataCadastroCong = new org.openswing.swing.client.LabelControl();
        txtNomeProduto = new org.openswing.swing.client.LabelControl();
        txtQuantidades = new org.openswing.swing.client.LabelControl();
        numericPesoUnitCongelados = new org.openswing.swing.client.NumericControl();
        txtPesoUnit = new org.openswing.swing.client.LabelControl();
        txtPesoTotal = new org.openswing.swing.client.LabelControl();
        numericPesoTotalCongelados = new org.openswing.swing.client.NumericControl();
        dateControlCong = new org.openswing.swing.client.DateControl();
        txtCod_Ingred1 = new org.openswing.swing.client.LabelControl();
        textCodCongelados = new org.openswing.swing.client.TextControl();
        jLabel1 = new javax.swing.JLabel();
        numericControlRequisicaoN = new org.openswing.swing.client.NumericControl();
        jLabel2 = new javax.swing.JLabel();
        textControlClasseProdCongelados = new org.openswing.swing.client.TextControl();
        jLabel3 = new javax.swing.JLabel();
        textControlSetorCongelados = new org.openswing.swing.client.TextControl();
        jLabel4 = new javax.swing.JLabel();
        textControlRespCongelados = new org.openswing.swing.client.TextControl();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Cadastro de Congelados (Inserir/Alterar)");
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanelHeader.setBackground(new java.awt.Color(153, 153, 153));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery_Factory_logo_127x50.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanelHeader.add(lblLogo);
        jPanelHeader.add(insertButtonCong);
        jPanelHeader.add(copyButtonCong);
        jPanelHeader.add(editButtonCong);
        jPanelHeader.add(deleteButtonCong);
        jPanelHeader.add(reloadButtonCong);
        jPanelHeader.add(saveButtonCong);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelHeader, gridBagConstraints);

        formCongelados.setVOClassName("com.bakeryfactory.VO.IngredienteVO");
        formCongelados.setCopyButton(copyButtonCong);
        formCongelados.setDeleteButton(deleteButtonCong);
        formCongelados.setEditButton(editButtonCong);
        formCongelados.setInsertButton(insertButtonCong);
        formCongelados.setReloadButton(reloadButtonCong);
        formCongelados.setSaveButton(saveButtonCong);
        formCongelados.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(textNomeIngred, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(numericQuantCongelados, gridBagConstraints);

        txtDataCadastroCong.setText("Data de Cadastro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(txtDataCadastroCong, gridBagConstraints);

        txtNomeProduto.setText("Produto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(txtNomeProduto, gridBagConstraints);

        txtQuantidades.setText("Quantidades:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(txtQuantidades, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(numericPesoUnitCongelados, gridBagConstraints);

        txtPesoUnit.setText("Peso Unitário:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(txtPesoUnit, gridBagConstraints);

        txtPesoTotal.setText("Peso Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(txtPesoTotal, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(numericPesoTotalCongelados, gridBagConstraints);

        dateControlCong.setCanCopy(false);
        dateControlCong.setRequired(true);
        dateControlCong.setToolTipText("Inserir Data de Cadastro do Ingrediente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(dateControlCong, gridBagConstraints);

        txtCod_Ingred1.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(txtCod_Ingred1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 250);
        formCongelados.add(textCodCongelados, gridBagConstraints);

        jLabel1.setText("Requisição Nº");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(numericControlRequisicaoN, gridBagConstraints);

        jLabel2.setText("Setor Solicitante");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(textControlClasseProdCongelados, gridBagConstraints);

        jLabel3.setText("Classe de Produto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formCongelados.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(textControlSetorCongelados, gridBagConstraints);

        jLabel4.setText("Responsável:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(textControlRespCongelados, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formCongelados.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        getContentPane().add(formCongelados, gridBagConstraints);

        getAccessibleContext().setAccessibleName("Cadastro de Congelados (Inserir/Alterar)");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongeladosDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongeladosDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongeladosDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongeladosDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new IngredienteDetalhe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.CopyButton copyButtonCong;
    private org.openswing.swing.client.DateControl dateControlCong;
    private org.openswing.swing.client.DeleteButton deleteButtonCong;
    private org.openswing.swing.client.EditButton editButtonCong;
    private org.openswing.swing.form.client.Form formCongelados;
    private org.openswing.swing.client.InsertButton insertButtonCong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JLabel lblLogo;
    private org.openswing.swing.client.NumericControl numericControlRequisicaoN;
    private org.openswing.swing.client.NumericControl numericPesoTotalCongelados;
    private org.openswing.swing.client.NumericControl numericPesoUnitCongelados;
    private org.openswing.swing.client.NumericControl numericQuantCongelados;
    private org.openswing.swing.client.ReloadButton reloadButtonCong;
    private org.openswing.swing.client.SaveButton saveButtonCong;
    private org.openswing.swing.client.TextControl textCodCongelados;
    private org.openswing.swing.client.TextControl textControlClasseProdCongelados;
    private org.openswing.swing.client.TextControl textControlRespCongelados;
    private org.openswing.swing.client.TextControl textControlSetorCongelados;
    private org.openswing.swing.client.TextControl textNomeIngred;
    private org.openswing.swing.client.LabelControl txtCod_Ingred1;
    private org.openswing.swing.client.LabelControl txtDataCadastroCong;
    private org.openswing.swing.client.LabelControl txtNomeProduto;
    private org.openswing.swing.client.LabelControl txtPesoTotal;
    private org.openswing.swing.client.LabelControl txtPesoUnit;
    private org.openswing.swing.client.LabelControl txtQuantidades;
    // End of variables declaration//GEN-END:variables
}
