/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import com.bakeryfactory.Controller.IngredientesController;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class Congelados extends InternalFrame {

    private Connection conn = null;

    /**
     * Creates new form Ingredientes Panificadora
     */
    public Congelados(Connection conn, IngredientesController ingredController) {
        this.conn = conn;
        try {
            initComponents();
            setSize(750, 300);
            gridControl_Congelados.setController(ingredController);
            gridControl_Congelados.setGridDataLocator(ingredController);
            //gridControlIngred.enableDrag("Grid1");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public void reloadData(){
        gridControl_Congelados.reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelHeader = new javax.swing.JPanel();
        lbl_Logo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        insertButton_ = new org.openswing.swing.client.InsertButton();
        editButton_ = new org.openswing.swing.client.EditButton();
        deleteButton_ = new org.openswing.swing.client.DeleteButton();
        reloadButton_ = new org.openswing.swing.client.ReloadButton();
        exportButton_ = new org.openswing.swing.client.ExportButton();
        importButton_ = new org.openswing.swing.client.ImportButton();
        navigatorBar_ = new org.openswing.swing.client.NavigatorBar();
        gridControl_Congelados = new org.openswing.swing.client.GridControl();
        integerCodCongelados = new org.openswing.swing.table.columns.client.IntegerColumn();
        codLookupRequisicao = new org.openswing.swing.table.columns.client.CodLookupColumn();
        dateDataCongelados = new org.openswing.swing.table.columns.client.DateColumn();
        textProdutoCongelados = new org.openswing.swing.table.columns.client.TextColumn();
        comboSetorClasseProd = new org.openswing.swing.table.columns.client.ComboColumn();
        comboSetorCongelados = new org.openswing.swing.table.columns.client.ComboColumn();
        textRespCongelados = new org.openswing.swing.table.columns.client.TextColumn();
        decimalPesoUnid = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalQuantidades = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalPesoTotal = new org.openswing.swing.table.columns.client.DecimalColumn();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos Congelados");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelHeader.setBackground(new java.awt.Color(153, 0, 0));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery_Factory_logo_127x50.png"))); // NOI18N
        lbl_Logo.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanelHeader.add(lbl_Logo);

        jLabelTitulo.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastros de Congelados");
        jPanelHeader.add(jLabelTitulo);
        jLabelTitulo.getAccessibleContext().setAccessibleName("Cadastro de Congelados");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelHeader, gridBagConstraints);

        jPanelButtons.setBackground(new java.awt.Color(153, 0, 0));
        jPanelButtons.add(insertButton_);
        jPanelButtons.add(editButton_);
        jPanelButtons.add(deleteButton_);
        jPanelButtons.add(reloadButton_);
        jPanelButtons.add(exportButton_);
        jPanelButtons.add(importButton_);
        jPanelButtons.add(navigatorBar_);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelButtons, gridBagConstraints);

        gridControl_Congelados.setDeleteButton(deleteButton_);
        gridControl_Congelados.setEditButton(editButton_);
        gridControl_Congelados.setExportButton(exportButton_);
        gridControl_Congelados.setFunctionId("ingredientes");
        gridControl_Congelados.setImportButton(importButton_);
        gridControl_Congelados.setInsertButton(insertButton_);
        gridControl_Congelados.setNavBar(navigatorBar_);
        gridControl_Congelados.setReloadButton(reloadButton_);
        gridControl_Congelados.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControl_Congelados.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        integerCodCongelados.setHeaderColumnName("Código");
        gridControl_Congelados.getColumnContainer().add(integerCodCongelados);

        codLookupRequisicao.setHeaderColumnName("Requisição Nº");
        gridControl_Congelados.getColumnContainer().add(codLookupRequisicao);

        dateDataCongelados.setColumnSortable(true);
        dateDataCongelados.setHeaderColumnName("Data");
        dateDataCongelados.setSortVersus(org.openswing.swing.util.java.Consts.ASC_SORTED);
        gridControl_Congelados.getColumnContainer().add(dateDataCongelados);

        textProdutoCongelados.setColumnSortable(true);
        textProdutoCongelados.setHeaderColumnName("Produto Descrição");
        textProdutoCongelados.setPreferredWidth(300);
        gridControl_Congelados.getColumnContainer().add(textProdutoCongelados);

        comboSetorClasseProd.setAutoFitColumn(true);
        comboSetorClasseProd.setColumnSortable(true);
        comboSetorClasseProd.setHeaderColumnName("Classe de Produtos");
        gridControl_Congelados.getColumnContainer().add(comboSetorClasseProd);

        comboSetorCongelados.setHeaderColumnName("Setor Solicitante");
        gridControl_Congelados.getColumnContainer().add(comboSetorCongelados);

        textRespCongelados.setHeaderColumnName("Responsável");
        gridControl_Congelados.getColumnContainer().add(textRespCongelados);

        decimalPesoUnid.setHeaderColumnName("Peso Unitário");
        gridControl_Congelados.getColumnContainer().add(decimalPesoUnid);

        decimalQuantidades.setHeaderColumnName("Quantidades");
        gridControl_Congelados.getColumnContainer().add(decimalQuantidades);

        decimalPesoTotal.setHeaderColumnName("Peso Total");
        gridControl_Congelados.getColumnContainer().add(decimalPesoTotal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl_Congelados, gridBagConstraints);
        gridControl_Congelados.getAccessibleContext().setAccessibleName("Cadastro Ingredientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.CodLookupColumn codLookupRequisicao;
    private org.openswing.swing.table.columns.client.ComboColumn comboSetorClasseProd;
    private org.openswing.swing.table.columns.client.ComboColumn comboSetorCongelados;
    private org.openswing.swing.table.columns.client.DateColumn dateDataCongelados;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalPesoTotal;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalPesoUnid;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalQuantidades;
    private org.openswing.swing.client.DeleteButton deleteButton_;
    private org.openswing.swing.client.EditButton editButton_;
    private org.openswing.swing.client.ExportButton exportButton_;
    private org.openswing.swing.client.GridControl gridControl_Congelados;
    private org.openswing.swing.client.ImportButton importButton_;
    private org.openswing.swing.client.InsertButton insertButton_;
    private org.openswing.swing.table.columns.client.IntegerColumn integerCodCongelados;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JLabel lbl_Logo;
    private org.openswing.swing.client.NavigatorBar navigatorBar_;
    private org.openswing.swing.client.ReloadButton reloadButton_;
    private org.openswing.swing.table.columns.client.TextColumn textProdutoCongelados;
    private org.openswing.swing.table.columns.client.TextColumn textRespCongelados;
    // End of variables declaration//GEN-END:variables
}
