/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import com.bakeryfactory.Controller.IngredientesController;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class IngredientesPanificadora extends InternalFrame {

    private Connection conn = null;

    /**
     * Creates new form Ingredientes Panificadora
     */
    public IngredientesPanificadora(Connection conn, IngredientesController ingredController) {
        this.conn = conn;
        try {
            initComponents();
            setSize(750, 300);
            gridControlIngred.setController(ingredController);
            gridControlIngred.setGridDataLocator(ingredController);
            //gridControlIngred.enableDrag("Grid1");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public void reloadData(){
        gridControlIngred.reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        insertButtonIngred = new org.openswing.swing.client.InsertButton();
        editButtonIngred = new org.openswing.swing.client.EditButton();
        deleteButtonIngred = new org.openswing.swing.client.DeleteButton();
        reloadButtonIngred = new org.openswing.swing.client.ReloadButton();
        exportButtonIngred = new org.openswing.swing.client.ExportButton();
        importButtonIngred = new org.openswing.swing.client.ImportButton();
        navigatorBarIngred = new org.openswing.swing.client.NavigatorBar();
        gridControlIngred = new org.openswing.swing.client.GridControl();
        dateDataIngred = new org.openswing.swing.table.columns.client.DateColumn();
        integerCodIngred = new org.openswing.swing.table.columns.client.IntegerColumn();
        textNomeIngred = new org.openswing.swing.table.columns.client.TextColumn();
        textTipoIngred = new org.openswing.swing.table.columns.client.TextColumn();
        decimalPesoIngred = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalUnidadeIngred = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalValorIngred = new org.openswing.swing.table.columns.client.DecimalColumn();

        setTitle("Cadastro de Ingredientes");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ata.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Ingredientes");
        jPanel1.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.add(insertButtonIngred);
        jPanel2.add(editButtonIngred);
        jPanel2.add(deleteButtonIngred);
        jPanel2.add(reloadButtonIngred);
        jPanel2.add(exportButtonIngred);
        jPanel2.add(importButtonIngred);
        jPanel2.add(navigatorBarIngred);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        gridControlIngred.setDeleteButton(deleteButtonIngred);
        gridControlIngred.setExportButton(exportButtonIngred);
        gridControlIngred.setFunctionId("ingredientes");
        gridControlIngred.setImportButton(importButtonIngred);
        gridControlIngred.setInsertButton(insertButtonIngred);
        gridControlIngred.setNavBar(navigatorBarIngred);
        gridControlIngred.setReloadButton(reloadButtonIngred);
        gridControlIngred.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControlIngred.setValueObjectClassName("com.bakeryfactory.VO.IngredientesVO");

        dateDataIngred.setColumnName("dataCadastroIngred");
        dateDataIngred.setColumnSortable(true);
        dateDataIngred.setHeaderColumnName("Data");
        dateDataIngred.setSortVersus(org.openswing.swing.util.java.Consts.ASC_SORTED);
        gridControlIngred.getColumnContainer().add(dateDataIngred);

        integerCodIngred.setColumnName("codigo");
        integerCodIngred.setHeaderColumnName("Codigo");
        gridControlIngred.getColumnContainer().add(integerCodIngred);

        textNomeIngred.setColumnName("nomeIngrediente");
        textNomeIngred.setColumnSortable(true);
        textNomeIngred.setHeaderColumnName("Nome dos Ingredientes");
        textNomeIngred.setPreferredWidth(300);
        gridControlIngred.getColumnContainer().add(textNomeIngred);

        textTipoIngred.setColumnName("tipoIngrediente");
        textTipoIngred.setColumnSortable(true);
        textTipoIngred.setHeaderColumnName("Tipo");
        textTipoIngred.setPreferredWidth(200);
        gridControlIngred.getColumnContainer().add(textTipoIngred);

        decimalPesoIngred.setHeaderColumnName("Peso");
        gridControlIngred.getColumnContainer().add(decimalPesoIngred);

        decimalUnidadeIngred.setColumnName("unidade");
        decimalUnidadeIngred.setHeaderColumnName("Unidades");
        gridControlIngred.getColumnContainer().add(decimalUnidadeIngred);

        decimalValorIngred.setColumnName("valor");
        decimalValorIngred.setHeaderColumnName("Valor R$");
        gridControlIngred.getColumnContainer().add(decimalValorIngred);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControlIngred, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DateColumn dateDataIngred;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalPesoIngred;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalUnidadeIngred;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalValorIngred;
    private org.openswing.swing.client.DeleteButton deleteButtonIngred;
    private org.openswing.swing.client.EditButton editButtonIngred;
    private org.openswing.swing.client.ExportButton exportButtonIngred;
    private org.openswing.swing.client.GridControl gridControlIngred;
    private org.openswing.swing.client.ImportButton importButtonIngred;
    private org.openswing.swing.client.InsertButton insertButtonIngred;
    private org.openswing.swing.table.columns.client.IntegerColumn integerCodIngred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.client.NavigatorBar navigatorBarIngred;
    private org.openswing.swing.client.ReloadButton reloadButtonIngred;
    private org.openswing.swing.table.columns.client.TextColumn textNomeIngred;
    private org.openswing.swing.table.columns.client.TextColumn textTipoIngred;
    // End of variables declaration//GEN-END:variables
}
