/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import com.bakeryfactory.Controller.IngredientesController;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class Ingredientes extends InternalFrame {

    private Connection conn = null;

    /**
     * Creates new form Ingredientes Panificadora
     */
    public Ingredientes(Connection conn, IngredientesController ingredController) {
        this.conn = conn;
        try {
            initComponents();
            setSize(750, 300);
            gridControlIngred.setController(ingredController);
            gridControlIngred.setGridDataLocator(ingredController);
            //gridControlIngred.enableDrag("Grid1");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public void reloadData(){
        gridControlIngred.reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        insertButtonIngred = new org.openswing.swing.client.InsertButton();
        editButtonIngred = new org.openswing.swing.client.EditButton();
        deleteButtonIngred = new org.openswing.swing.client.DeleteButton();
        reloadButtonIngred = new org.openswing.swing.client.ReloadButton();
        exportButtonIngred = new org.openswing.swing.client.ExportButton();
        importButtonIngred = new org.openswing.swing.client.ImportButton();
        navigatorBarIngred = new org.openswing.swing.client.NavigatorBar();
        gridControlIngred = new org.openswing.swing.client.GridControl();
        dateData_Ingred = new org.openswing.swing.table.columns.client.DateColumn();
        integerCod_Ingred = new org.openswing.swing.table.columns.client.IntegerColumn();
        textNome_Ingred = new org.openswing.swing.table.columns.client.TextColumn();
        textTipo_Ingred = new org.openswing.swing.table.columns.client.TextColumn();
        decimalPeso_Ingred = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalUnidade_Ingred = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalValor_Ingred = new org.openswing.swing.table.columns.client.DecimalColumn();

        setTitle("Cadastro de Ingredientes");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery_Factory_logo_127x50.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel1.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Ingredientes");
        jPanel1.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.add(insertButtonIngred);
        jPanel2.add(editButtonIngred);
        jPanel2.add(deleteButtonIngred);
        jPanel2.add(reloadButtonIngred);
        jPanel2.add(exportButtonIngred);
        jPanel2.add(importButtonIngred);
        jPanel2.add(navigatorBarIngred);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        gridControlIngred.setDeleteButton(deleteButtonIngred);
        gridControlIngred.setEditButton(editButtonIngred);
        gridControlIngred.setExportButton(exportButtonIngred);
        gridControlIngred.setFunctionId("ingredientes");
        gridControlIngred.setImportButton(importButtonIngred);
        gridControlIngred.setInsertButton(insertButtonIngred);
        gridControlIngred.setNavBar(navigatorBarIngred);
        gridControlIngred.setReloadButton(reloadButtonIngred);
        gridControlIngred.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControlIngred.setValueObjectClassName("com.bakeryfactory.VO.IngredientesVO");
        gridControlIngred.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        dateData_Ingred.setColumnName(dateData_Ingred.getColumnName());
        dateData_Ingred.setColumnSortable(true);
        dateData_Ingred.setHeaderColumnName("Data");
        dateData_Ingred.setSortVersus(org.openswing.swing.util.java.Consts.ASC_SORTED);
        gridControlIngred.getColumnContainer().add(dateData_Ingred);

        integerCod_Ingred.setColumnName(integerCod_Ingred.getColumnName());
        integerCod_Ingred.setHeaderColumnName("Código");
        gridControlIngred.getColumnContainer().add(integerCod_Ingred);

        textNome_Ingred.setColumnName(textNome_Ingred.getColumnName());
        textNome_Ingred.setColumnSortable(true);
        textNome_Ingred.setHeaderColumnName("Nome dos Ingredientes");
        textNome_Ingred.setPreferredWidth(300);
        gridControlIngred.getColumnContainer().add(textNome_Ingred);

        textTipo_Ingred.setColumnFilterable(true);
        textTipo_Ingred.setColumnName(textTipo_Ingred.getColumnName());
        textTipo_Ingred.setColumnSortable(true);
        textTipo_Ingred.setHeaderColumnName("Tipo");
        textTipo_Ingred.setPreferredWidth(200);
        gridControlIngred.getColumnContainer().add(textTipo_Ingred);

        decimalPeso_Ingred.setColumnName(decimalPeso_Ingred.getColumnName());
        decimalPeso_Ingred.setHeaderColumnName("Peso");
        gridControlIngred.getColumnContainer().add(decimalPeso_Ingred);

        decimalUnidade_Ingred.setColumnName(decimalUnidade_Ingred.getColumnName());
        decimalUnidade_Ingred.setHeaderColumnName("Unidades");
        gridControlIngred.getColumnContainer().add(decimalUnidade_Ingred);

        decimalValor_Ingred.setColumnName(decimalValor_Ingred.getColumnName());
        decimalValor_Ingred.setHeaderColumnName("Valor R$");
        gridControlIngred.getColumnContainer().add(decimalValor_Ingred);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControlIngred, gridBagConstraints);
        gridControlIngred.getAccessibleContext().setAccessibleName("Cadastro Ingredientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DateColumn dateData_Ingred;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalPeso_Ingred;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalUnidade_Ingred;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalValor_Ingred;
    private org.openswing.swing.client.DeleteButton deleteButtonIngred;
    private org.openswing.swing.client.EditButton editButtonIngred;
    private org.openswing.swing.client.ExportButton exportButtonIngred;
    private org.openswing.swing.client.GridControl gridControlIngred;
    private org.openswing.swing.client.ImportButton importButtonIngred;
    private org.openswing.swing.client.InsertButton insertButtonIngred;
    private org.openswing.swing.table.columns.client.IntegerColumn integerCod_Ingred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.client.NavigatorBar navigatorBarIngred;
    private org.openswing.swing.client.ReloadButton reloadButtonIngred;
    private org.openswing.swing.table.columns.client.TextColumn textNome_Ingred;
    private org.openswing.swing.table.columns.client.TextColumn textTipo_Ingred;
    // End of variables declaration//GEN-END:variables
}
