/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import com.bakeryfactory.Controller.IngredientesController;
import com.bakeryfactory.Controller.SetorController;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class Setor extends InternalFrame {

    private Connection conn = null;

    /**
     * Creates new form 
     */
    public Setor(Connection conn, SetorController setorController) {
        this.conn = conn;
        try {
            initComponents();
            setSize(750, 300);
            gridControl_Setores.setController(setorController);
            gridControl_Setores.setGridDataLocator(setorController);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public void reloadData(){
        gridControl_Setores.reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelHeader = new javax.swing.JPanel();
        lbl_Logo = new javax.swing.JLabel();
        jLabelTituloHeader = new javax.swing.JLabel();
        jPanelButtonsPlace = new javax.swing.JPanel();
        codLookupControl1 = new org.openswing.swing.client.CodLookupControl();
        insertButtonSetor = new org.openswing.swing.client.InsertButton();
        editButtonSetor = new org.openswing.swing.client.EditButton();
        deleteButtonSetor = new org.openswing.swing.client.DeleteButton();
        reloadButtonSetor = new org.openswing.swing.client.ReloadButton();
        exportButtonSetor = new org.openswing.swing.client.ExportButton();
        importButtonSetor = new org.openswing.swing.client.ImportButton();
        navigatorBarSetor = new org.openswing.swing.client.NavigatorBar();
        gridControl_Setores = new org.openswing.swing.client.GridControl();
        dateDataSetor = new org.openswing.swing.table.columns.client.DateColumn();
        integerCodSetor = new org.openswing.swing.table.columns.client.IntegerColumn();
        textNomeSetores = new org.openswing.swing.table.columns.client.TextColumn();
        textRespSetor = new org.openswing.swing.table.columns.client.TextColumn();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Setores");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelHeader.setBackground(new java.awt.Color(153, 0, 0));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery_Factory_logo_127x50.png"))); // NOI18N
        lbl_Logo.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanelHeader.add(lbl_Logo);

        jLabelTituloHeader.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabelTituloHeader.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloHeader.setText("Cadastro de Setores");
        jPanelHeader.add(jLabelTituloHeader);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelHeader, gridBagConstraints);

        jPanelButtonsPlace.setBackground(new java.awt.Color(153, 0, 0));
        jPanelButtonsPlace.add(codLookupControl1);
        jPanelButtonsPlace.add(insertButtonSetor);
        jPanelButtonsPlace.add(editButtonSetor);
        jPanelButtonsPlace.add(deleteButtonSetor);
        jPanelButtonsPlace.add(reloadButtonSetor);
        jPanelButtonsPlace.add(exportButtonSetor);
        jPanelButtonsPlace.add(importButtonSetor);
        jPanelButtonsPlace.add(navigatorBarSetor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelButtonsPlace, gridBagConstraints);

        gridControl_Setores.setDeleteButton(deleteButtonSetor);
        gridControl_Setores.setEditButton(editButtonSetor);
        gridControl_Setores.setExportButton(exportButtonSetor);
        gridControl_Setores.setFunctionId("ingredientes");
        gridControl_Setores.setImportButton(importButtonSetor);
        gridControl_Setores.setInsertButton(insertButtonSetor);
        gridControl_Setores.setNavBar(navigatorBarSetor);
        gridControl_Setores.setReloadButton(reloadButtonSetor);
        gridControl_Setores.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControl_Setores.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        dateDataSetor.setColumnSortable(true);
        dateDataSetor.setHeaderColumnName("Data");
        dateDataSetor.setSortVersus(org.openswing.swing.util.java.Consts.ASC_SORTED);
        gridControl_Setores.getColumnContainer().add(dateDataSetor);

        integerCodSetor.setHeaderColumnName("Código");
        gridControl_Setores.getColumnContainer().add(integerCodSetor);

        textNomeSetores.setColumnSortable(true);
        textNomeSetores.setHeaderColumnName("Nome Setor");
        textNomeSetores.setPreferredWidth(300);
        gridControl_Setores.getColumnContainer().add(textNomeSetores);

        textRespSetor.setColumnFilterable(true);
        textRespSetor.setColumnSortable(true);
        textRespSetor.setHeaderColumnName("Responsável Setor");
        textRespSetor.setPreferredWidth(200);
        gridControl_Setores.getColumnContainer().add(textRespSetor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl_Setores, gridBagConstraints);
        gridControl_Setores.getAccessibleContext().setAccessibleName("Cadastro Ingredientes");

        getAccessibleContext().setAccessibleName("Cadastro de Setores");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.CodLookupControl codLookupControl1;
    private org.openswing.swing.table.columns.client.DateColumn dateDataSetor;
    private org.openswing.swing.client.DeleteButton deleteButtonSetor;
    private org.openswing.swing.client.EditButton editButtonSetor;
    private org.openswing.swing.client.ExportButton exportButtonSetor;
    private org.openswing.swing.client.GridControl gridControl_Setores;
    private org.openswing.swing.client.ImportButton importButtonSetor;
    private org.openswing.swing.client.InsertButton insertButtonSetor;
    private org.openswing.swing.table.columns.client.IntegerColumn integerCodSetor;
    private javax.swing.JLabel jLabelTituloHeader;
    private javax.swing.JPanel jPanelButtonsPlace;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JLabel lbl_Logo;
    private org.openswing.swing.client.NavigatorBar navigatorBarSetor;
    private org.openswing.swing.client.ReloadButton reloadButtonSetor;
    private org.openswing.swing.table.columns.client.TextColumn textNomeSetores;
    private org.openswing.swing.table.columns.client.TextColumn textRespSetor;
    // End of variables declaration//GEN-END:variables
}
