/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import com.bakeryfactory.view.Ingredientes;
import java.sql.Connection;
import org.openswing.swing.client.DeleteButton;
import org.openswing.swing.client.EditButton;
import org.openswing.swing.client.SaveButton;
import org.openswing.swing.form.client.Form;
import org.openswing.swing.form.client.FormController;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class SetorDetalhe extends InternalFrame {
    
    private Connection conn = null;

    public SetorDetalhe(Connection conn, FormController dataController) {
        try {
            this.conn = conn;
             initComponents();
             formSetor.setFormController(dataController);
             setSize(590,440);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public Form getForm1(){
        return formSetor;
        
    }
    
    public SaveButton getSaveButton() {
        return saveButtonSetor;
    }

    public DeleteButton getDeleteButton() {
        return deleteButtonSetor;
    }

    public EditButton getEditButton() {
        return editButtonSetor;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelControlsPlace = new javax.swing.JPanel();
        jPanelButtonPlace = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        insertButtonSetor = new org.openswing.swing.client.InsertButton();
        copyButtonSetor = new org.openswing.swing.client.CopyButton();
        editButtonSetor = new org.openswing.swing.client.EditButton();
        deleteButtonSetor = new org.openswing.swing.client.DeleteButton();
        reloadButtonSetor = new org.openswing.swing.client.ReloadButton();
        saveButtonSetor = new org.openswing.swing.client.SaveButton();
        formSetor = new org.openswing.swing.form.client.Form();
        textNomeIngred = new org.openswing.swing.client.TextControl();
        textCodIngred = new org.openswing.swing.client.TextControl();
        txtData_Ingred = new org.openswing.swing.client.LabelControl();
        txtNome_Ingred = new org.openswing.swing.client.LabelControl();
        txtPeso_Ingred1 = new org.openswing.swing.client.LabelControl();
        dateControlIngred = new org.openswing.swing.client.DateControl();
        txtCod_Ingred1 = new org.openswing.swing.client.LabelControl();
        textNomeIngred1 = new org.openswing.swing.client.TextControl();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Setores (Inserir/Alterar)");
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        getContentPane().add(jPanelControlsPlace, gridBagConstraints);

        jPanelButtonPlace.setBackground(new java.awt.Color(0, 153, 153));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery_Factory_logo_127x50.png"))); // NOI18N
        lblLogo.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanelButtonPlace.add(lblLogo);
        jPanelButtonPlace.add(insertButtonSetor);
        jPanelButtonPlace.add(copyButtonSetor);
        jPanelButtonPlace.add(editButtonSetor);
        jPanelButtonPlace.add(deleteButtonSetor);

        reloadButtonSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonSetorActionPerformed(evt);
            }
        });
        jPanelButtonPlace.add(reloadButtonSetor);
        jPanelButtonPlace.add(saveButtonSetor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelButtonPlace, gridBagConstraints);

        formSetor.setVOClassName("com.bakeryfactory.VO.IngredienteVO");
        formSetor.setCopyButton(copyButtonSetor);
        formSetor.setDeleteButton(deleteButtonSetor);
        formSetor.setEditButton(editButtonSetor);
        formSetor.setInsertButton(insertButtonSetor);
        formSetor.setReloadButton(reloadButtonSetor);
        formSetor.setSaveButton(saveButtonSetor);
        formSetor.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formSetor.add(textNomeIngred, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 250);
        formSetor.add(textCodIngred, gridBagConstraints);

        txtData_Ingred.setText("Data de Cadastro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formSetor.add(txtData_Ingred, gridBagConstraints);

        txtNome_Ingred.setText("Nome do Setor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formSetor.add(txtNome_Ingred, gridBagConstraints);

        txtPeso_Ingred1.setText("Responsável Setor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formSetor.add(txtPeso_Ingred1, gridBagConstraints);

        dateControlIngred.setCanCopy(false);
        dateControlIngred.setRequired(true);
        dateControlIngred.setToolTipText("Inserir Data de Cadastro do Ingrediente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formSetor.add(dateControlIngred, gridBagConstraints);

        txtCod_Ingred1.setText("Código");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        formSetor.add(txtCod_Ingred1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        formSetor.add(textNomeIngred1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        getContentPane().add(formSetor, gridBagConstraints);

        getAccessibleContext().setAccessibleName("Cadastro de Setores (Inserir/Alterar)");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadButtonSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reloadButtonSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetorDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetorDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetorDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetorDetalhe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new IngredienteDetalhe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.client.CopyButton copyButtonSetor;
    private org.openswing.swing.client.DateControl dateControlIngred;
    private org.openswing.swing.client.DeleteButton deleteButtonSetor;
    private org.openswing.swing.client.EditButton editButtonSetor;
    private org.openswing.swing.form.client.Form formSetor;
    private org.openswing.swing.client.InsertButton insertButtonSetor;
    private javax.swing.JPanel jPanelButtonPlace;
    private javax.swing.JPanel jPanelControlsPlace;
    private javax.swing.JLabel lblLogo;
    private org.openswing.swing.client.ReloadButton reloadButtonSetor;
    private org.openswing.swing.client.SaveButton saveButtonSetor;
    private org.openswing.swing.client.TextControl textCodIngred;
    private org.openswing.swing.client.TextControl textNomeIngred;
    private org.openswing.swing.client.TextControl textNomeIngred1;
    private org.openswing.swing.client.LabelControl txtCod_Ingred1;
    private org.openswing.swing.client.LabelControl txtData_Ingred;
    private org.openswing.swing.client.LabelControl txtNome_Ingred;
    private org.openswing.swing.client.LabelControl txtPeso_Ingred1;
    // End of variables declaration//GEN-END:variables
}
