/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bakeryfactory.view;

import com.bakeryfactory.Controller.IngredientesController;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Claudinei Aparecido Perboni
 */
public class UsuarioCadastro extends InternalFrame {

    private Connection conn = null;

    /**
     * Creates new form Ingredientes Panificadora
     */
    public UsuarioCadastro(Connection conn, IngredientesController ingredController) {
        this.conn = conn;
        try {
            initComponents();
            setSize(750, 300);
            gridControl_Usuarios.setController(ingredController);
            gridControl_Usuarios.setGridDataLocator(ingredController);
            //gridControlIngred.enableDrag("Grid1");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public void reloadData(){
        gridControl_Usuarios.reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelHeader = new javax.swing.JPanel();
        lbl_Logo = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        insertButton_ = new org.openswing.swing.client.InsertButton();
        editButton_ = new org.openswing.swing.client.EditButton();
        deleteButton_ = new org.openswing.swing.client.DeleteButton();
        reloadButton_ = new org.openswing.swing.client.ReloadButton();
        exportButton_ = new org.openswing.swing.client.ExportButton();
        importButton_ = new org.openswing.swing.client.ImportButton();
        navigatorBar_ = new org.openswing.swing.client.NavigatorBar();
        gridControl_Usuarios = new org.openswing.swing.client.GridControl();
        dateDataUsuario = new org.openswing.swing.table.columns.client.DateColumn();
        integerCodUsuario = new org.openswing.swing.table.columns.client.IntegerColumn();
        textNomeUsuario = new org.openswing.swing.table.columns.client.TextColumn();
        textLoginUsuario = new org.openswing.swing.table.columns.client.TextColumn();
        formattedTextSenha = new org.openswing.swing.table.columns.client.FormattedTextColumn();
        comboColumnTipo = new org.openswing.swing.table.columns.client.ComboColumn();

        setTitle("Cadastro de Usuários");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelHeader.setBackground(new java.awt.Color(153, 0, 0));

        lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bakery_Factory_logo_127x50.png"))); // NOI18N
        lbl_Logo.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanelHeader.add(lbl_Logo);

        jLabelTitulo.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastros de Usuários");
        jPanelHeader.add(jLabelTitulo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelHeader, gridBagConstraints);

        jPanelButtons.setBackground(new java.awt.Color(153, 0, 0));
        jPanelButtons.add(insertButton_);
        jPanelButtons.add(editButton_);
        jPanelButtons.add(deleteButton_);
        jPanelButtons.add(reloadButton_);
        jPanelButtons.add(exportButton_);
        jPanelButtons.add(importButton_);
        jPanelButtons.add(navigatorBar_);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelButtons, gridBagConstraints);

        gridControl_Usuarios.setDeleteButton(deleteButton_);
        gridControl_Usuarios.setEditButton(editButton_);
        gridControl_Usuarios.setExportButton(exportButton_);
        gridControl_Usuarios.setFunctionId("usuarios");
        gridControl_Usuarios.setImportButton(importButton_);
        gridControl_Usuarios.setInsertButton(insertButton_);
        gridControl_Usuarios.setNavBar(navigatorBar_);
        gridControl_Usuarios.setReloadButton(reloadButton_);
        gridControl_Usuarios.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControl_Usuarios.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        dateDataUsuario.setColumnSortable(true);
        dateDataUsuario.setHeaderColumnName("Data");
        dateDataUsuario.setSortVersus(org.openswing.swing.util.java.Consts.ASC_SORTED);
        gridControl_Usuarios.getColumnContainer().add(dateDataUsuario);

        integerCodUsuario.setHeaderColumnName("Código");
        gridControl_Usuarios.getColumnContainer().add(integerCodUsuario);

        textNomeUsuario.setColumnSortable(true);
        textNomeUsuario.setHeaderColumnName("Nome do Usuário");
        textNomeUsuario.setPreferredWidth(300);
        gridControl_Usuarios.getColumnContainer().add(textNomeUsuario);

        textLoginUsuario.setColumnFilterable(true);
        textLoginUsuario.setColumnSortable(true);
        textLoginUsuario.setHeaderColumnName("Login");
        textLoginUsuario.setPreferredWidth(200);
        gridControl_Usuarios.getColumnContainer().add(textLoginUsuario);

        formattedTextSenha.setHeaderColumnName("Senha");
        gridControl_Usuarios.getColumnContainer().add(formattedTextSenha);

        comboColumnTipo.setEditableOnInsert(true);
        comboColumnTipo.setHeaderColumnName("Tipo Usuario");
        gridControl_Usuarios.getColumnContainer().add(comboColumnTipo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl_Usuarios, gridBagConstraints);
        gridControl_Usuarios.getAccessibleContext().setAccessibleName("Cadastro Usuarios");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.ComboColumn comboColumnTipo;
    private org.openswing.swing.table.columns.client.DateColumn dateDataUsuario;
    private org.openswing.swing.client.DeleteButton deleteButton_;
    private org.openswing.swing.client.EditButton editButton_;
    private org.openswing.swing.client.ExportButton exportButton_;
    private org.openswing.swing.table.columns.client.FormattedTextColumn formattedTextSenha;
    private org.openswing.swing.client.GridControl gridControl_Usuarios;
    private org.openswing.swing.client.ImportButton importButton_;
    private org.openswing.swing.client.InsertButton insertButton_;
    private org.openswing.swing.table.columns.client.IntegerColumn integerCodUsuario;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JLabel lbl_Logo;
    private org.openswing.swing.client.NavigatorBar navigatorBar_;
    private org.openswing.swing.client.ReloadButton reloadButton_;
    private org.openswing.swing.table.columns.client.TextColumn textLoginUsuario;
    private org.openswing.swing.table.columns.client.TextColumn textNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
